#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Mar 30, 2022 11:08:56 AM CDT  platform: Windows NT
#    Mar 30, 2022 11:09:55 AM CDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import Math

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = Math.Toplevel1(_top1)
    root.mainloop()

def Quit(*args):
    print('Math_support.Quit')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def v1(*args):
    print('Math_support.v1')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def v2_m1(*args):
    print('Math_support.v2_m1')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def v2_m2(*args):
    print('Math_support.v2_m2')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def quit(*args):
    print('Math_support.quit')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

if __name__ == '__main__':
    Math.start_up()





